import { test, expect } from '@playwright/test';

test('testing ToDoList app, validating 5 test cases.', async ({ page }) => {
  await page.goto('https://www.techglobal-training.com/frontend/project-6');
  await page.getByText('Test Case 01 - Todo-App Modal').click();
  await expect(page.getByRole('heading', { name: 'TODO List' })).toBeVisible();
  await page.getByPlaceholder('New todo').click();
  await page.getByPlaceholder('New todo').fill('abc');
  await page.getByRole('button', { name: 'ADD' }).click();
  await expect(page.locator('div').filter({ hasText: /^abc$/ }).nth(1)).toBeVisible();
  await expect(page.getByRole('button', { name: 'ADD' })).toBeVisible();
  await page.locator('div').filter({ hasText: /^abc$/ }).nth(1).click();
  await page.goto('https://www.techglobal-training.com/frontend/project-6');
  await page.getByText('No tasks found!').click();
  await expect(page.getByRole('navigation')).toContainText('No tasks found!');
  await page.getByText('Test Case 02 - Single Task').click();
  await page.getByPlaceholder('New todo').click();
  await page.getByPlaceholder('New todo').fill('Task 2');
  await page.getByRole('button', { name: 'ADD' }).click();
  await expect(page.getByText('Task 2')).toBeVisible();
  await page.getByPlaceholder('New todo').click();
  await page.getByPlaceholder('New todo').fill('Task 3');
  await page.getByRole('button', { name: 'ADD' }).click();
  await page.getByPlaceholder('New todo').click();
  await page.getByPlaceholder('New todo').fill('Task 4');
  await page.getByRole('button', { name: 'ADD' }).click();
  await page.getByPlaceholder('New todo').click();
  await page.getByPlaceholder('New todo').fill('Task 5');
  await page.getByRole('button', { name: 'ADD' }).click();
  await expect(page.locator('#panel')).toContainText('Task 2');
  await page.locator('div').filter({ hasText: /^Task 2$/ }).first().click();
  await page.getByText('Test Case 04 - Search and').click();
  await page.getByText('Test Case 05 - Task').click();
  await page.getByPlaceholder('New todo').click();
  await page.getByPlaceholder('New todo').fill('Task 5ieeeeeeeeeeeeeeeeeeeeeeeeee');
  await page.getByRole('button', { name: 'ADD' }).click();
  await expect(page.getByRole('navigation')).toContainText('Error: Todo cannot be more than 30 characters!');
  await page.getByPlaceholder('New todo').click();
  await page.getByPlaceholder('New todo').fill('Taskeeeeeeeeeeeeee');
  await page.getByRole('button', { name: 'ADD' }).click();
  await page.getByRole('button', { name: 'ADD' }).click();
  await expect(page.getByRole('navigation')).toContainText('Error: You already have Taskeeeeeeeeeeeeee in your todo list.');
});